# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: i'm jonthebeef.
email: me@jonthebeef.xyz
description: > # this means to ignore newlines until "baseurl:"
  Manchester based digital product strategist and designer. Startup founder, music and food lover, and geek. Musings, portfolio, and thinking.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonthebeef.xyz" # the base hostname & protocol for your site
twitter_username: jonthebeef

# Build settings
markdown: kramdown

# Google services
google_analytics: UA—82044029-1

# Gems
gems: ['jekyll-emoji']
emoji:
  format: emojione-svg # default html
  ascii: true # default false
  shortname: true # default true
  src: "/assets/imgs/emojis" # defaults to "https://cdn.jsdelivr.net/emojione/assets/#{ext}"

gems:
  - jemoji
